/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ext5OpenLayers3.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'Ext5OpenLayers3.view.MainViewViewModel',
        'Ext5OpenLayers3.view.MainViewViewController',
        'Ext5OpenLayers3.view.OpenLayers3',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'menuPanel',
            width: 250,
            layout: 'accordion',
            collapseDirection: 'left',
            collapsible: true,
            title: 'Menu',
            items: [
                {
                    xtype: 'panel',
                    title: 'Group 1',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menu1',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Group 2',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menu2',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Group 3',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menu3',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'center',
            itemId: 'contentPanel',
            layout: 'fit',
            title: 'Map',
            items: [
                {
                    xtype: 'openlayers3',
                    layers: [
                        new ol.layer.Tile({
                            source: new ol.source.MapQuest({
                                layer: 'osm'
                            })
                        })
                    ],
                    listeners: {
                        mapRender: 'onMapRender'
                    }
                }
            ]
        }
    ]

});